package main

func main() {
	//exercise_01.Run()
	//exercise_02.Run()
	//exercise_03.Run()
	//exercise_04.Run()
	//exercise_05.Run()
	//exercise_06.Run()
	//exercise_07.Run()
	//exercise_08.Run()
	//exercise_09.Run()
	//exercise_10.Run()
	//exercise_11.Run()
	//exercise_12.Run()
	//exercise_13.Run()
	//exercise_14.Run()
	//exercise_15.Run()
	//exercise_16.Run()
	//exercise_17.Run()
	//exercise_18.Run()
	//exercise_19.Run()
	//exercise_20.Run()
	//exercise_21.Run()
	//exercise_22.Run()
	//exercise_23.Run()
	//exercise_24.Run()
	//exercise_25.Run()
	//exercise_26.Run()
}
